version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  app:
    image: node-crud-ejs-app
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/crudDB

volumes:
  mongodb_data:
